# Generated by Django 2.1.5 on 2019-02-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('tabletop', models.IntegerField()),
                ('hz', models.IntegerField()),
                ('skin', models.IntegerField()),
                ('skingl', models.IntegerField()),
                ('plastic', models.IntegerField()),
                ('facade', models.IntegerField()),
                ('loop', models.IntegerField()),
                ('hitch', models.IntegerField()),
                ('roof', models.IntegerField()),
                ('baguette', models.IntegerField()),
                ('handle', models.IntegerField()),
            ],
        ),
    ]
