# Generated by Django 2.1.5 on 2019-02-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_oreder'),
    ]

    operations = [
        migrations.AddField(
            model_name='oreder',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
