# Generated by Django 2.1.5 on 2019-02-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_oreder_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oreder',
            new_name='Order',
        ),
    ]
