# Generated by Django 2.1.5 on 2019-02-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190203_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Base')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabletop_end', models.IntegerField()),
                ('tabletop_edge', models.IntegerField()),
                ('plinth', models.IntegerField()),
                ('plinth_cap', models.IntegerField()),
                ('wall_panel', models.IntegerField()),
                ('wall_cap', models.IntegerField()),
                ('rail', models.IntegerField()),
                ('baluster', models.IntegerField()),
                ('drying', models.IntegerField()),
                ('backlight', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Order')),
            ],
        ),
        migrations.AddField(
            model_name='cupboard',
            name='price_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Price'),
        ),
    ]
