# Generated by Django 2.1.5 on 2019-02-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190203_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='facade',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='base',
            name='roof',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
